spring.application.name=eventhubri

# =========================================================
# MySQL Database
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/eventhub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================================================
# JWT Security
# =========================================================

security.jwt.issuer=eventhub-api

# 15 minutes
security.jwt.expiration-ms=900000

# Use an environment variable instead of hardcoding this
security.jwt.secret=bOdIngVt+3xtvPyIzZJanN5e/riI8erUoygajeVIG6U=


# =========================================================
# Server
# =========================================================

server.port=8080


# =========================================================
# Logging
# =========================================================

logging.level.org.springframework.security=INFO