spring.application.name=eventhubri

# =========================================================
# MySQL Database
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/eventhub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================================================
# JWT Security
# =========================================================

security.jwt.issuer=eventhub-api

# 15 minutes
security.jwt.expiration-ms=900000

# Use an environment variable instead of hardcoding this
security.jwt.secret=bOdIngVt+3xtvPyIzZJanN5e/riI8erUoygajeVIG6U=


# =========================================================
# Server
# =========================================================

server.port=8080


# =========================================================
# Logging
# =========================================================

logging.level.org.springframework.security=INFO


# =========================================================
# Cloudflare R2 Storage
# =========================================================

cloudflare.r2.account-id=a17b66fe5009657296e401f4bc4f765a
cloudflare.r2.access-key=038f8823d40286944de9d4ba03c4d6bb
cloudflare.r2.secret-key=fad9675a32477acf1789c5ca15245e694f8599f62a4537aff74a526ee8b3a88c
cloudflare.r2.bucket=eventhub
# Public bucket URL (e.g. https://pub-xxxx.r2.dev or custom domain)
cloudflare.r2.public-url=https://pub-12c922fd7e194b3596d8613b01b04a62.r2.dev


# =========================================================
# Multipart Upload
# =========================================================

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB