-- Clean up database state prior to inserting attendee test data
DELETE FROM session_selections;
DELETE FROM registrations;
DELETE FROM attendees;
DELETE FROM organizers;
DELETE FROM users;

-- Parent table: users (100 Records)
INSERT INTO users (user_id, name, email) VALUES
    ('USR-001', 'John Doe', 'john.doe@example.com'),
    ('USR-002', 'Jane Smith', 'jane.smith@example.com'),
    ('USR-003', 'Johnny Appleseed', 'johnny@example.com'),
    ('USR-004', 'Alice Johnson', 'alice.johnson@example.com'),
    ('USR-005', 'Bob Brown', 'bob.brown@example.com'),
    ('USR-006', 'Charlie Davis', 'charlie.davis@example.com'),
    ('USR-007', 'Diana Prince', 'diana.prince@example.com'),
    ('USR-008', 'Evan Wright', 'evan.wright@example.com'),
    ('USR-009', 'Fiona Gallagher', 'fiona.gallagher@example.com'),
    ('USR-010', 'George Clark', 'george.clark@example.com'),
    ('USR-011', 'Hannah Abbott', 'hannah.abbott@example.com'),
    ('USR-012', 'Ian Malcolm', 'ian.malcolm@example.com'),
    ('USR-013', 'Julia Roberts', 'julia.roberts@example.com'),
    ('USR-014', 'Kevin Bacon', 'kevin.bacon@example.com'),
    ('USR-015', 'Laura Croft', 'laura.croft@example.com'),
    ('USR-016', 'Michael Scott', 'michael.scott@example.com'),
    ('USR-017', 'Nina Williams', 'nina.williams@example.com'),
    ('USR-018', 'Oscar Martinez', 'oscar.martinez@example.com'),
    ('USR-019', 'Pam Beesly', 'pam.beesly@example.com'),
    ('USR-020', 'Quinn Fabray', 'quinn.fabray@example.com'),
    ('USR-021', 'Rachel Green', 'rachel.green@example.com'),
    ('USR-022', 'Steve Rogers', 'steve.rogers@example.com'),
    ('USR-023', 'Tony Stark', 'tony.stark@example.com'),
    ('USR-024', 'Ursula Buffay', 'ursula.buffay@example.com'),
    ('USR-025', 'Victor Stone', 'victor.stone@example.com'),
    ('USR-026', 'Wanda Maximoff', 'wanda.maximoff@example.com'),
    ('USR-027', 'Xavier Charles', 'xavier.charles@example.com'),
    ('USR-028', 'Yennefer Vengerberg', 'yennefer@example.com'),
    ('USR-029', 'Zachary Levi', 'zachary.levi@example.com'),
    ('USR-030', 'Johnathan Wick', 'johnathan.wick@example.com'),
    ('USR-031', 'Jane Doe', 'jane.doe@example.com'),
    ('USR-032', 'Johnny Storm', 'johnny.storm@example.com'),
    ('USR-033', 'Aaron Paul', 'aaron.paul@example.com'),
    ('USR-034', 'Beth Rick', 'beth.rick@example.com'),
    ('USR-035', 'Caitlin Snow', 'caitlin.snow@example.com'),
    ('USR-036', 'David Miller', 'david.miller@example.com'),
    ('USR-037', 'Emily Watson', 'emily.watson@example.com'),
    ('USR-038', 'Frank Castle', 'frank.castle@example.com'),
    ('USR-039', 'Grace Hopper', 'grace.hopper@example.com'),
    ('USR-040', 'Harry Potter', 'harry.potter@example.com'),
    ('USR-041', 'Iris West', 'iris.west@example.com'),
    ('USR-042', 'Jack Sparrow', 'jack.sparrow@example.com'),
    ('USR-043', 'Karen Page', 'karen.page@example.com'),
    ('USR-044', 'Luke Skywalker', 'luke.skywalker@example.com'),
    ('USR-045', 'Mia Wallace', 'mia.wallace@example.com'),
    ('USR-046', 'Noah Bennet', 'noah.bennet@example.com'),
    ('USR-047', 'Olivia Dunham', 'olivia.dunham@example.com'),
    ('USR-048', 'Peter Parker', 'peter.parker@example.com'),
    ('USR-049', 'Quentin Tarantino', 'quentin@example.com'),
    ('USR-050', 'Ronald Weasley', 'ronald.weasley@example.com'),
    ('USR-051', 'Sarah Connor', 'sarah.connor@example.com'),
    ('USR-052', 'Thomas Anderson', 'thomas.anderson@example.com'),
    ('USR-053', 'Ulysses Grant', 'ulysses.grant@example.com'),
    ('USR-054', 'Veronica Mars', 'veronica.mars@example.com'),
    ('USR-055', 'Walter White', 'walter.white@example.com'),
    ('USR-056', 'Xena Warrior', 'xena@example.com'),
    ('USR-057', 'Yara Greyjoy', 'yara.greyjoy@example.com'),
    ('USR-058', 'Zoe Saldana', 'zoe.saldana@example.com'),
    ('USR-059', 'John Smith', 'john.smith@example.com'),
    ('USR-060', 'Johnson Reed', 'johnson.reed@example.com'),
    ('USR-061', 'Alan Turing', 'alan.turing@example.com'),
    ('USR-062', 'Barbara Gordon', 'barbara.gordon@example.com'),
    ('USR-063', 'Cisco Ramon', 'cisco.ramon@example.com'),
    ('USR-064', 'Dick Grayson', 'dick.grayson@example.com'),
    ('USR-065', 'Elena Gilbert', 'elena.gilbert@example.com'),
    ('USR-066', 'Felicity Smoak', 'felicity.smoak@example.com'),
    ('USR-067', 'Garrick Ollivander', 'garrick@example.com'),
    ('USR-068', 'Hal Jordan', 'hal.jordan@example.com'),
    ('USR-069', 'Ivy Poison', 'ivy.poison@example.com'),
    ('USR-070', 'James Gordon', 'james.gordon@example.com'),
    ('USR-071', 'Kate Bishop', 'kate.bishop@example.com'),
    ('USR-072', 'Loki Laufeyson', 'loki@example.com'),
    ('USR-073', 'Matt Murdock', 'matt.murdock@example.com'),
    ('USR-074', 'Natasha Romanoff', 'natasha.romanoff@example.com'),
    ('USR-075', 'Oswald Cobblepot', 'oswald@example.com'),
    ('USR-076', 'Peggy Carter', 'peggy.carter@example.com'),
    ('USR-077', 'Quill Peter', 'quill.peter@example.com'),
    ('USR-078', 'Reed Richards', 'reed.richards@example.com'),
    ('USR-079', 'Sam Wilson', 'sam.wilson@example.com'),
    ('USR-080', 'T''Challa Udaku', 'tchalla@example.com'),
    ('USR-081', 'Umar Johnson', 'umar.johnson@example.com'),
    ('USR-082', 'Vision Android', 'vision@example.com'),
    ('USR-083', 'Wade Wilson', 'wade.wilson@example.com'),
    ('USR-084', 'Xander Harris', 'xander.harris@example.com'),
    ('USR-085', 'Yogi Bear', 'yogi.bear@example.com'),
    ('USR-086', 'Zatanna Zatara', 'zatanna@example.com'),
    ('USR-087', 'John Watson', 'john.watson@example.com'),
    ('USR-088', 'John Locke', 'john.locke@example.com'),
    ('USR-089', 'Jane Eyre', 'jane.eyre@example.com'),
    ('USR-090', 'Janet Van Dyne', 'janet.vandyne@example.com'),
    ('USR-091', 'Arthur Dent', 'arthur.dent@example.com'),
    ('USR-092', 'Bruce Wayne', 'bruce.wayne@example.com'),
    ('USR-093', 'Clark Kent', 'clark.kent@example.com'),
    ('USR-094', 'Daisy Johnson', 'daisy.johnson@example.com'),
    ('USR-095', 'Edward Elric', 'edward.elric@example.com'),
    ('USR-096', 'Ford Prefect', 'ford.prefect@example.com'),
    ('USR-097', 'Gwen Stacy', 'gwen.stacy@example.com'),
    ('USR-098', 'Hank Pym', 'hank.pym@example.com'),
    ('USR-099', 'Indy Jones', 'indy.jones@example.com'),
    ('USR-100', 'John Boyega', 'john.boyega@example.com');

-- Subclass table: attendees (100 Records matching users)
INSERT INTO attendees (user_id, attendee_id) VALUES
    ('USR-001', 'ATT-001'),
    ('USR-002', 'ATT-002'),
    ('USR-003', 'ATT-003'),
    ('USR-004', 'ATT-004'),
    ('USR-005', 'ATT-005'),
    ('USR-006', 'ATT-006'),
    ('USR-007', 'ATT-007'),
    ('USR-008', 'ATT-008'),
    ('USR-009', 'ATT-009'),
    ('USR-010', 'ATT-010'),
    ('USR-011', 'ATT-011'),
    ('USR-012', 'ATT-012'),
    ('USR-013', 'ATT-013'),
    ('USR-014', 'ATT-014'),
    ('USR-015', 'ATT-015'),
    ('USR-016', 'ATT-016'),
    ('USR-017', 'ATT-017'),
    ('USR-018', 'ATT-018'),
    ('USR-019', 'ATT-019'),
    ('USR-020', 'ATT-020'),
    ('USR-021', 'ATT-021'),
    ('USR-022', 'ATT-022'),
    ('USR-023', 'ATT-023'),
    ('USR-024', 'ATT-024'),
    ('USR-025', 'ATT-025'),
    ('USR-026', 'ATT-026'),
    ('USR-027', 'ATT-027'),
    ('USR-028', 'ATT-028'),
    ('USR-029', 'ATT-029'),
    ('USR-030', 'ATT-030'),
    ('USR-031', 'ATT-031'),
    ('USR-032', 'ATT-032'),
    ('USR-033', 'ATT-033'),
    ('USR-034', 'ATT-034'),
    ('USR-035', 'ATT-035'),
    ('USR-036', 'ATT-036'),
    ('USR-037', 'ATT-037'),
    ('USR-038', 'ATT-038'),
    ('USR-039', 'ATT-039'),
    ('USR-040', 'ATT-040'),
    ('USR-041', 'ATT-041'),
    ('USR-042', 'ATT-042'),
    ('USR-043', 'ATT-043'),
    ('USR-044', 'ATT-044'),
    ('USR-045', 'ATT-045'),
    ('USR-046', 'ATT-046'),
    ('USR-047', 'ATT-047'),
    ('USR-048', 'ATT-048'),
    ('USR-049', 'ATT-049'),
    ('USR-050', 'ATT-050'),
    ('USR-051', 'ATT-051'),
    ('USR-052', 'ATT-052'),
    ('USR-053', 'ATT-053'),
    ('USR-054', 'ATT-054'),
    ('USR-055', 'ATT-055'),
    ('USR-056', 'ATT-056'),
    ('USR-057', 'ATT-057'),
    ('USR-058', 'ATT-058'),
    ('USR-059', 'ATT-059'),
    ('USR-060', 'ATT-060'),
    ('USR-061', 'ATT-061'),
    ('USR-062', 'ATT-062'),
    ('USR-063', 'ATT-063'),
    ('USR-064', 'ATT-064'),
    ('USR-065', 'ATT-065'),
    ('USR-066', 'ATT-066'),
    ('USR-067', 'ATT-067'),
    ('USR-068', 'ATT-068'),
    ('USR-069', 'ATT-069'),
    ('USR-070', 'ATT-070'),
    ('USR-071', 'ATT-071'),
    ('USR-072', 'ATT-072'),
    ('USR-073', 'ATT-073'),
    ('USR-074', 'ATT-074'),
    ('USR-075', 'ATT-075'),
    ('USR-076', 'ATT-076'),
    ('USR-077', 'ATT-077'),
    ('USR-078', 'ATT-078'),
    ('USR-079', 'ATT-079'),
    ('USR-080', 'ATT-080'),
    ('USR-081', 'ATT-081'),
    ('USR-082', 'ATT-082'),
    ('USR-083', 'ATT-083'),
    ('USR-084', 'ATT-084'),
    ('USR-085', 'ATT-085'),
    ('USR-086', 'ATT-086'),
    ('USR-087', 'ATT-087'),
    ('USR-088', 'ATT-088'),
    ('USR-089', 'ATT-089'),
    ('USR-090', 'ATT-090'),
    ('USR-091', 'ATT-091'),
    ('USR-092', 'ATT-092'),
    ('USR-093', 'ATT-093'),
    ('USR-094', 'ATT-094'),
    ('USR-095', 'ATT-095'),
    ('USR-096', 'ATT-096'),
    ('USR-097', 'ATT-097'),
    ('USR-098', 'ATT-098'),
    ('USR-099', 'ATT-099'),
    ('USR-100', 'ATT-100');