package com.pointwest.bootcamp.eventhubri.billing.dto.response;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import com.pointwest.bootcamp.eventhubri.billing.enums.InvoiceStatus;

// No request DTO: invoices are generated by the billing job from usage data,
// never authored directly by a client.
public record InvoiceResponseDto(
        Long id,
        Long organizerId,
        LocalDate billingPeriodStart,
        LocalDate billingPeriodEnd,
        BigDecimal totalAmount,
        InvoiceStatus invoiceStatus,
        LocalDateTime issuedAt,
        LocalDateTime paidAt,
        List<InvoiceItemResponseDto> items
) {
}
