package com.pointwest.bootcamp.eventhubri.core.exception.enums;

import lombok.Getter;

@Getter
public enum EventhubErrorCode {
    // Global & Validation
    VALIDATION_FAILED("VALIDATION_FAILED", 400),
    MALFORMED_REQUEST_BODY("MALFORMED_REQUEST_BODY", 400),
    INVALID_PARAMETER_TYPE("INVALID_PARAMETER_TYPE", 400),
    HTTP_METHOD_NOT_SUPPORTED("HTTP_METHOD_NOT_SUPPORTED", 405),

    // Auth & Authorization
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED", 401),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED", 401),
    AUTH_ACCESS_DENIED("AUTH_ACCESS_DENIED", 403),
    USER_NOT_IN_ORGANIZATION("USER_NOT_IN_ORGANIZATION", 403),

    // Event Management (Controller & Service)
    EVENT_NOT_FOUND("EVENT_NOT_FOUND", 404),
    EVENT_ALREADY_EXISTS("EVENT_ALREADY_EXISTS", 409),
    EVENT_FULL("EVENT_FULL", 409),
    EVENT_CAPACITY_EXCEEDED("EVENT_CAPACITY_EXCEEDED", 409),
    EVENT_CAPACITY_CONFLICT("EVENT_CAPACITY_CONFLICT", 409),
    INVALID_EVENT_TIMELINE("INVALID_EVENT_TIMELINE", 422), // e.g., start_time > end_time
    EVENT_START_IN_PAST("EVENT_START_IN_PAST", 422),
    EVENT_INVALID_STATE_TRANSITION("EVENT_INVALID_STATE_TRANSITION", 409), // e.g., DRAFT to COMPLETED
    EVENT_CANNOT_BE_MODIFIED("EVENT_CANNOT_BE_MODIFIED", 409), // Trying to update/delete a CANCELLED/COMPLETED event
    EVENT_HAS_ACTIVE_REGISTRATIONS("EVENT_HAS_ACTIVE_REGISTRATIONS", 409), // Deletion conflict

    // Organizations
    ORGANIZATION_NOT_FOUND("ORGANIZATION_NOT_FOUND", 404),
    ORGANIZATION_INACTIVE("ORGANIZATION_INACTIVE", 403), // Status is SUSPENDED or PENDING

    // Event Registrations & Check-ins
    REGISTRATION_NOT_FOUND("REGISTRATION_NOT_FOUND", 404),
    ATTENDEE_ALREADY_REGISTERED("ATTENDEE_ALREADY_REGISTERED", 409),
    INVALID_QR_CODE("INVALID_QR_CODE", 400),
    ATTENDEE_ALREADY_CHECKED_IN("ATTENDEE_ALREADY_CHECKED_IN", 409),

    // Agendas & Sessions
    AGENDA_NOT_FOUND("AGENDA_NOT_FOUND", 404),
    SESSION_NOT_FOUND("SESSION_NOT_FOUND", 404),
    SESSION_TIME_OVERLAP("SESSION_TIME_OVERLAP", 409),
    SPEAKER_DOUBLE_BOOKED("SPEAKER_DOUBLE_BOOKED", 409),

    // Billing & Invoices
    INVOICE_NOT_FOUND("INVOICE_NOT_FOUND", 404),
    PAYMENT_OVERDUE("PAYMENT_OVERDUE", 402);

    private final String errorCode;
    private final int httpStatusCode;

    EventhubErrorCode(String errorCode, int httpStatusCode){
        this.errorCode = errorCode;
        this.httpStatusCode = httpStatusCode;
    }
}
