package com.pointwest.bootcamp.eventhubri.core.exception.enums;

import lombok.Getter;

@Getter
public enum EventhubErrorCode {
    // Global & Validation
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", 404),
    BUSINESS_RULE_VIOLATION("BUSINESS_RULE_VIOLATION", 400),
    ACCESS_DENIED("ACCESS_DENIED", 403),

    // Auth & User Exceptions
    USER_ALREADY_EXISTS("USER_ALREADY_EXISTS", 409),
    USER_NOT_FOUND("USER_NOT_FOUND", 404),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS", 401),
    USER_INACTIVE("USER_INACTIVE", 403),

    // Refresh Token Exceptions
    INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN", 401),
    REFRESH_TOKEN_REUSE_DETECTED("REFRESH_TOKEN_REUSE_DETECTED", 401),
    REFRESH_TOKEN_EXPIRED("REFRESH_TOKEN_EXPIRED", 401),
    TOKEN_HASHING_FAILED("TOKEN_HASHING_FAILED", 500),

    // Organization Exceptions
    ORGANIZER_NOT_FOUND("ORGANIZER_NOT_FOUND", 404),
    ORGANIZATION_NOT_FOUND("ORGANIZATION_NOT_FOUND", 404),
    ORGANIZATION_ALREADY_EXISTS("ORGANIZATION_ALREADY_EXISTS", 409),
    ORGANIZATION_INACTIVE("ORGANIZATION_INACTIVE", 403),

    // Event Management
    EVENT_NOT_FOUND("EVENT_NOT_FOUND", 404),
    EVENT_ACCESS_DENIED("EVENT_ACCESS_DENIED", 403),
    INVALID_EVENT_TIMELINE("INVALID_EVENT_TIMELINE", 422),
    INVALID_EVENT_SCHEDULE("INVALID_EVENT_SCHEDULE", 422),
    INVALID_EVENT_TYPE_REQUIREMENTS("INVALID_EVENT_TYPE_REQUIREMENTS", 400),

    // Registration Exceptions
    REGISTRATION_NOT_FOUND("REGISTRATION_NOT_FOUND", 404),
    REGISTRATION_ALREADY_EXISTS("REGISTRATION_ALREADY_EXISTS", 409),
    REGISTRATION_ALREADY_CANCELLED("REGISTRATION_ALREADY_CANCELLED", 409),
    REGISTRATION_PERIOD_CLOSED("REGISTRATION_PERIOD_CLOSED", 422),
    REGISTRATION_ACCESS_DENIED("REGISTRATION_ACCESS_DENIED", 403),

    // Employee & Profile
    EMPLOYEE_NOT_FOUND("EMPLOYEE_NOT_FOUND", 404),
    INVALID_PROFILE_IMAGE("INVALID_PROFILE_IMAGE", 400),
    PROFILE_IMAGE_UPLOAD_FAILED("PROFILE_IMAGE_UPLOAD_FAILED", 500),

    // Communication
    NOTIFICATION_FORBIDDEN("NOTIFICATION_FORBIDDEN", 403),
    EVENT_NOTIFICATION_NOT_FOUND("EVENT_NOTIFICATION_NOT_FOUND", 404),
    RECIPIENT_NOT_FOUND("RECIPIENT_NOT_FOUND", 404),
    RECIPIENT_NOT_REGISTERED("RECIPIENT_NOT_REGISTERED", 404),
    NO_REGISTRATIONS_FOR_EVENT("NO_REGISTRATIONS_FOR_EVENT", 404),

    // Billing & Invoices
    PAYMENT_OVERDUE("PAYMENT_OVERDUE", 402);

    private final String errorCode;
    private final int httpStatusCode;

    EventhubErrorCode(String errorCode, int httpStatusCode) {
        this.errorCode = errorCode;
        this.httpStatusCode = httpStatusCode;
    }
}
